back on sh

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,41 +1,30 @@
-#!/usr/bin/env python3
-
-# for i in $PWD/*; do
-#   echo $i
-# done
-# exit 0
+#!/usr/bin/env sh
+# vim:syntax=bash
 #
-# submodules() {
-#   git submodule update --init
-#   git submodule foreach git checkout main
-# }
-#
-# OS="$(uname)" ARCH="$(arch)"
-#
-# bootstrap_brew() {
-#   # bootstrap homebrew on a mac
-#   if [ $OS = 'Darwin' ] && ! command -v brew >/dev/null; then
-#     # arm64 and non-arm archs on mac have different homebrew paths
-#     [ $ARCH = 'arm64' ] && PREFIX='/opt/homebrew' || PREFIX='/usr/local'
-#     [ ! -f $PREFIX/bin/brew ] && echo 'brew not found ._.' && exit 1
-#     # clutch a brew link
-#     eval "$($PREFIX/bin/brew shellenv)"
-#   fi
-# }
-#
-# # check that stow is installed
-# if ! command -v stow >/dev/null; then
-#   echo 'stow not found ._.' && exit 1
-# fi
-#
-# stow -t ~ -d . config
+# It is the responsibility of the user to make sure that this script
+# is called from the directory that this script is located in.
 
+submodules() {
+  git submodule update --init
+  git submodule foreach git checkout main
+}
 
-from sys import platform
+OS="$(uname)" ARCH="$(arch)"
 
-def main():
-    pass
+bootstrap_brew() {
+  # bootstrap homebrew on a mac
+  if [ $OS = 'Darwin' ] && ! command -v brew >/dev/null; then
+    # arm64 and non-arm archs on mac have different homebrew paths
+    [ $ARCH = 'arm64' ] && PREFIX='/opt/homebrew' || PREFIX='/usr/local'
+    [ ! -f $PREFIX/bin/brew ] && echo 'brew not found ._.' && exit 1
+    # clutch a brew link
+    eval "$($PREFIX/bin/brew shellenv)"
+  fi
+}
 
+# check that stow is installed
+if ! command -v stow >/dev/null; then
+  echo 'stow not found ._.' && exit 1
+fi
 
-if __name__ == "__main__":
-    main()
+stow --restow -t ~ -d . .config
